version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin@2020
    ports:
      - '3306:3306'
    volumes:
      - /Users/erl/data/mysql:/var/lib/mysql
      - /Users/erl/GiteeWork/docker-compose/mysql/conf.d:/etc/mysql/conf.d
